version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-qwerty}
      POSTGRES_DB: ${DB_NAME:-crud-app}
    ports:
      - "${DB_PORT:-5433}:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "${ADMINER_PORT:-8008}:8080"